version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - ~/portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000/tcp"
      - "9443:9443/tcp"
    restart: always