services:
  cloudflare:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    environment:
      API_KEY: ${CF_API_KEY}
      ZONE: ${CF_ZONE}
      SUBDOMAIN: ${CF_SUBDOMAIN}
      PROXIED: ${CF_PROXIED}
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - .env