services:
  unifi:
    image: jacobalberty/unifi:v7.5.176
    container_name: unifi
    volumes:
      - ~/unifi:/unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
    environment:
      TZ: Asia/Bangkok
    restart: always