services:
  mitmweb-wireguard:
    image: mitmproxy/mitmproxy:latest
    container_name: mitmweb-wireguard
    command: mitmweb --web-host 0.0.0.0 --set web_password='${MITM_WEB_PASSWORD}' --mode wireguard
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8080:8080"       # Proxy
      - "8081:8081"       # Web UI
      - "51820:51820/udp" # Wireguard
    volumes:
      - ~/mitmweb/mitmproxy:/home/mitmproxy/.mitmproxy  # Save config/certs
    restart: unless-stopped
    env_file:
      - .env