services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    volumes:
      - ~/wireguard/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "8021:51821"
    environment:
      WG_HOST: ${WG_HOST}
      PASSWORD_HASH: ${WG_PASSWORD}
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - .env