services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: ss-server
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    command: ss-server -s 0.0.0.0 -p 8388 -k ${SS_PASSWORD} -m chacha20-ietf-poly1305
    restart: unless-stopped
    env_file:
      - .env