services:
  homebridge:
    image: homebridge/homebridge
    container_name: homebridge
    network_mode: host
    volumes:
      - ~/homebridge:/homebridge
    environment:
      TZ: Asia/Bangkok
    restart: always