version: "3.9"

services:
  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    network_mode: host
    volumes:
      - ~/homebridge:/homebridge
    environment:
      TZ: Asia/Bangkok
      HOMEBRIDGE_CONFIG_UI: 1
      HOMEBRIDGE_CONFIG_UI_PORT: 8050
    restart: always